# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Pokemon_Stage_3_Client
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(Pokemon_Stage_3_Client.pri)
win32:RC_FILE = Pokemon_Stage_3_Client.rc
